name: Build LaTeX Document
on:
  pull_request_target:
    branches: 
      - protected
    types: [closed]

jobs:
  build_latex:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone source repo
        uses: actions/checkout@v4
        with:
          path: Documents
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Clone destination repo
        uses: actions/checkout@v4
        with:
          path: Output
          repository: lisienskenderi/pdf-test
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: Compile LaTeX document
        run: |
          ls -la
          cd Output
          ls -la
          git pull

          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@github.com
          cd ..
          cd Documents
          ls -la
          git branch -a
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@github.com
          cd ..
          docker run -i --rm -v "$(pwd):/work" -w /work -u "$(id -u):$(id -g)" ghcr.io/xu-cheng/texlive-full bash -c '
          shopt -s globstar
          set -e
          set -m

          for path in ${{ steps.changed-files.outputs.all_changed_files }}; do(
            echo "$path was changed"
            if [[ "$(basename "$path")" != "Verbale_Esterno.tex" ]] && [[ "$(basename "$path")" != "Verbale_Interno.tex" ]] && [[ $path == *.tex ]] 
            then
              new_name=$(python Version_finder.py $path)

              git add "${path}"
              git add "${new_name}"
              
              path_no_under="${new_name//_/ }"
              name=$(basename "$new_name")
              name_no_ext="${name%.*}"
              new_only_name="Aggiornato $name_no_ext"

              git commit -m "$new_only_name"
              cd "$(dirname "$path")"
              latexmk -pdf "$(basename "$new_name")"
            else 
              echo "Questo è un template"
            fi
          )done
          cd Output

          git add .
          git status

          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Cancellato file deprecati"
          else
            echo "No changes to commit."
          fi
          cd ..
          '

      - name: upload pdf
        run: |
          shopt -s globstar
          set -e
          cd Documents

          if find "Documents" -type f -name "*.pdf" -print -quit 2>/dev/null; then
            for path in Documents/**/*.pdf; do (
              echo "$path"
              dirname=$(dirname "$path")
              echo "${dirname}"
              new_dirname="Output/$dirname"
              dirname_no_under="${new_dirname//_/ }"
              echo "$new_dirname"
              name_old=$(basename "$path")
              name_no_ext="${name_old%.*}"
              name_no_under="${name_no_ext//_/ }"
              name="${name_old//_/ }"
              echo "$dirname_no_under"
              new_name="Aggiornato $name_no_under"
              # Create the directory in Output having the same structure/path that it had in Documents removing the ./Documents part with its parent directories
              if [ ! -d "$dirname_no_under" ]; then
                mkdir -p "${dirname_no_under}"
                echo "created: $dirname_no_under"
              fi
              # Move $path in Output saving the same structure/path that it had in Documents removing the ./Documents part
              mv -f "$path" "${dirname_no_under}"
              mv -f "$dirname_no_under"/"$name_old" "$dirname_no_under"/"$name"
              echo 1
              path_no_under="${path//_/ }"
              cd ..
              cd Output
              echo 2
              ls -la
              git add "${path_no_under}"
              #git status
              echo 3
              git commit -m "$new_name"
              echo 4
              cd ..
              cd Documents
              echo 5
            ) done
          fi
          cd ..
          cd Output
          git config --global push.autoSetupRemote true
          git status
          git push
          cd .. 
          cd Documents
          git push